name: Tox

on: [push, pull_request]

jobs:
  tox-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install --upgrade pip
      - run: pip install tox
      - run: tox -e lint  # Perhaps use ${{ job.name }}

  tox-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install --upgrade pip
      - run: pip install tox
      - run: tox -e docs || true  # Fix error and remove "|| true"!

  tox-docs-linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install --upgrade pip
      - run: pip install tox
      - run: tox -e docs-linkcheck || true  # Fix error and remove "|| true"!

  build:
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        os: [ubuntu-latest]  # [macos-latest, ubuntu-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']
        django-version: ["==3.2.*", "==4.2.*"]
        exclude:
        # Django 3.2 don't supports python 3.11
          - python-version: 3.11
            django-version: "==3.2.*"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key:
            -${{ matrix.python-version }}-v1-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            -${{ matrix.python-version }}-v1-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade tox tox-gh-actions

      - name: Tox tests
        run: |
          tox -v

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          name: Python ${{ matrix.python-version }}
