name: tox
on: [push, pull_request]
jobs:
  tox-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - run: pip install --upgrade pip
      - run: pip install tox
      - run: tox -e lint  # Perhaps use ${{ job.name }}

  tox-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - run: pip install --upgrade pip
      - run: pip install tox
      - run: tox -e docs || true  # Fix error and remove "|| true"!

  tox-docs-linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - run: pip install --upgrade pip
      - run: pip install tox
      - run: tox -e docs-linkcheck || true  # Fix error and remove "|| true"!

  tox:
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        os: [ubuntu-latest]  # [macos-latest, ubuntu-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10']
        django-version: ["==3.2.*", "==4.0.*", "==4.1.*"]
#      exclude:
#      # Django 4.0 no longer supports python 3.7
#      - python-version: 3.7
#        django-version: "==4.0.*"
      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python }}
        - run: pip install --upgrade pip
        - run: pip install tox
        - run: tox -e py
